services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: htmlOverWire
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    environment:
      - MONGO_DB_URI=mongodb://root:rootpassword@mongo:27017/htmlOverWire?authSource=admin
      - DB_NAME=htmlOverWire
      - SERVER_PORT=8080
      - WEBSOCKET_PORT=8081
    ports:
      - "8080:8080"
      - "8081:8081"
volumes:
  mongodb_data_container:
